WebAdvert.Web/Models/Accounts/ConfirmModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace WebAdvert.Web.Models.Accounts
{
    public class ConfirmModel
    {
        [Required(ErrorMessage = "Email is required")]
        [Display(Name = "Email")]
        [EmailAddress]
        public string Email { get; set; }
        [Required(ErrorMessage = "Code is required")]
        public string Code { get; set; }
    }
}

WebAdvert.Web/Models/Accounts/LoginModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace WebAdvert.Web.Models.Accounts
{
    public class LoginModel
    {
        [Required(ErrorMessage = "Email is required")]
        [Display(Name = "Email")]
        [EmailAddress]
        public string Email { get; set; }
        [Required]
        [DataType(DataType.Password)]
        [StringLength(6, ErrorMessage = "Password must be at least six characters long!")]
        [Display(Name = "Password")]
        public string Password { get; set; }
        [Display(Name = "Remember Me")]
        public bool RememberMe { get; set; }
    }
}

WebAdvert.Web/Models/Accounts/RememberModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace WebAdvert.Web.Models.Accounts
{
    public class RememberModel
    {
        [Required]
        [EmailAddress]
        [Display(Name = "Email")]
        public string Email { get; set; }
    }
}

WebAdvert.Web/Models/Accounts/ResetModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebAdvert.Web.Models.Accounts
{
    public class ResetModel
    {
        public string Email { get; set; }
        public string Code { get; set; }
        public string Password { get; set; }
        //public string ConfirmPassword { get; set; }
    }
}

WebAdvert.Web/Models/Accounts/SignupModel.cs
using System.ComponentModel.DataAnnotations;

namespace WebAdvert.Web.Models.Accounts
{
    public class SignupModel
    {
        [Required]
        [EmailAddress]
        [Display(Name = "Email")]
        public string Email { get; set; }
        
        [Required]
        [DataType(DataType.Password)]
        [StringLength(6, ErrorMessage ="Password must be at least six characters long!")]
        [Display(Name ="Password")]
        public string Password { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Compare("Password", ErrorMessage = "Password and ist confirmation do not match")]
        public string ConfirmPassword { get; set; }
    }
}

WebAdvert.Web/Models/AdvertManagement/CreateAdvertViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace WebAdvert.Web.Models.AdvertManagement
{
    public class CreateAdvertViewModel
    {
        [Required(ErrorMessage="Title is required")]
        public string Title { get; set; }

        public string Description { get; set; }
        [Required(ErrorMessage = "Prices is required")]
        [DataType(DataType.Currency)]
        public double Price { get; set; }
    }
}

WebAdvert.Web/Models/ErrorViewModel.cs
using System;

namespace WebAdvert.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebAdvert.Web/Controllers/AdvertManagementController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using AdvertApi.Models;
using AutoMapper;
using Microsoft.AspNetCore.Http;
using WebAdvert.Web.Models.AdvertManagement;
using WebAdvert.Web.ServiceClients;
using WebAdvert.Web.Services;

namespace WebAdvert.Web.Controllers
{
    public class AdvertManagementController : Controller
    {
        private readonly IFileUploader _fileUploader;
        private readonly IAdvertApiClient _advertApiClient;
        private readonly IMapper _mapper;

        public AdvertManagementController(IFileUploader fileUploader, IAdvertApiClient advertApiClient, IMapper mapper)
        {
            _fileUploader = fileUploader;
            _advertApiClient = advertApiClient;
            _mapper = mapper;
        }

        public IActionResult Create(CreateAdvertViewModel model)
        {
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateAdvertViewModel model, IFormFile imageFile)
        {
            if (ModelState.IsValid)
            {
                var advertModel = _mapper.Map<AdvertModel>(model);
                var apiResponse = await _advertApiClient.Create(advertModel);
                var id = apiResponse.Id;
                var fileName = "";

                if (imageFile != null)
                {
                    fileName = !string.IsNullOrEmpty(imageFile.FileName) ? Path.GetFileName(imageFile.FileName) : id;
                    var filePath = $"{id}{fileName}";

                    try
                    {
                        using (var readStream = imageFile.OpenReadStream())
                        {
                            var result = await _fileUploader.UploadFileAsync(filePath, readStream);
                            if(!result)
                                throw new Exception("Could not upload the image to file repository. Please see the logs for details.");
                        }

                        await _advertApiClient.Confirm(new AdvertConfirmModel { Id = id});

                        return RedirectToAction("Index", "Home");
                    }
                    catch (Exception e)
                    {
                        Console.WriteLine(e);
                        return StatusCode(500, e);
                    }
                }
            }
            return View();
        }
    }
}

WebAdvert.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using WebAdvert.Web.Models;

namespace WebAdvert.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }
        [Authorize]
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebAdvert.Web/Views/Accounts/Confirm.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model WebAdvert.Web.Models.Accounts.ConfirmModel

<div class="row">
    <div class="col-md-4">
        <form method="post" asp-controller="Accounts" asp-action="Confirm">
            <div asp-validation-summary="All" class="text-danger"/>
                <div class="form-group">
                    <label asp-for="Email"></label>
                    <input asp-for="Email" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>

            <div class="form-group">
                <label asp-for="Code"></label>
                <input asp-for="Code" />
                <span asp-validation-for="Code" class="text-danger"></span>
            </div>

            <button type="submit">Confirm</button>
        </form>
    </div>
</div>

WebAdvert.Web/Views/Accounts/Login.cshtml
@model WebAdvert.Web.Models.Accounts.LoginModel

<div class="row">
    <div class="col-md-4">
        <h4>Login using your email address and password</h4>
        <h5>
            <a asp-controller="Accounts" asp-action="Signup">
                If your are not a member you can sign up here
            </a>
        </h5>
        <hr/>
        
        <form method="post" asp-controller="Accounts" asp-action="Login">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Email"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Password"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <div class="checkbox">
                    <label asp-for="RememberMe"></label>
                    <input asp-for="RememberMe"/>
                    @Html.DisplayName("Remember Me")
                </div>
            </div>
            <h5>
                <a asp-controller="Accounts" asp-action="Remember">
                    If you forget your password, you can reset here
                </a>
            </h5>
            <button type="submit">Login</button>
        </form>
    </div>
</div>

WebAdvert.Web/Views/Accounts/Remember.cshtml
@model WebAdvert.Web.Models.Accounts.RememberModel

<div class="row">
    <div class="cold-md-4">
        <form method="post" asp-controller="Accounts" asp-action="Remember">
            <h4>Remember password </h4>
            <hr />
            <div asp-validation-summary="All" class="text-danger" />

            <div class="form-group">
                <label asp-for="Email"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            
            <button type="submit" class="btn btn-default">SignUp</button>
        </form>
    </div>
</div>

WebAdvert.Web/Views/Accounts/Reset.cshtml
@model WebAdvert.Web.Models.Accounts.ResetModel

<div class="row">
    <div class="cold-md-4">
        <form method="post" asp-controller="Accounts" asp-action="Reset">
            <h4>Remember password </h4>
            <hr />
            <div asp-validation-summary="All" class="text-danger" />
            
            <div class="form-group">
                <label asp-for="Code"></label>
                <input asp-for="Code" class="form-control" />
                <span asp-validation-for="Code" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <label asp-for="Email"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Password"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            
            <button type="submit" class="btn btn-default">Change Password</button>
        </form>
    </div>
</div>

WebAdvert.Web/Views/Accounts/Signup.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "SignUp Page";
}
@model WebAdvert.Web.Models.Accounts.SignupModel

<div class="row">
    <div class="cold-md-4">
        <form method="post" asp-controller="Accounts" asp-action="Signup">
            <h4>Create a new account </h4>
            <hr />
            <div asp-validation-summary="All" class="text-danger"/>

            <div class="form-group">
                <label asp-for="Email"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Password"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="ConfirmPassword"></label>
                <input asp-for="ConfirmPassword" class="form-control" />
                <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
            </div>
            
            <button type="submit" class="btn btn-default">SignUp</button>
        </form>
    </div>
</div>

WebAdvert.Web/Views/AdvertManagement/Create.cshtml
@model WebAdvert.Web.Models.AdvertManagement.CreateAdvertViewModel

<div class="row">
    <div class="col-md-6">
        <form asp-controller="AdvertManagement" asp-action="Create" method="post" enctype="multipart/form-data">
            <div class="form-group">
                <label asp-for="Title"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Description"></label>
                <input asp-for="Description" class="form-control" />
            </div>

            <div class="form-group">
                <label asp-for="Price"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <input type="file" name="imageFile" value="Upload an image"/>
            </div> 
            <button type="submit" class="btn btn-default">Create</button>
        </form>
    </div>
</div>

WebAdvert.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

WebAdvert.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebAdvert.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebAdvert.Web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - WebAdvert.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>